version: "3.9"

services:
  
  nginx-and-front:
    build:
      context: ./front
      args:
        - front_files=${FRONT_FILES}
    image: nginx-cruncho:${TAG}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker-data/nginx-conf:/etc/nginx/conf.d:ro
      - ./docker-data/certbot/conf:/etc/letsencrypt:ro
      - ./docker-data/certbot/www:/var/www/certbot:ro
    networks:
      - cruncho-network
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - backend-cruncho

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./docker-data/certbot/conf:/etc/letsencrypt:rw
      - ./docker-data/certbot/www:/var/www/certbot:rw
    networks:
      - cruncho-network
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    depends_on:
      - backend-cruncho

  backend-cruncho:
    build:
      context: ./back
    image: backend-cruncho:${TAG}
    networks:
      - cruncho-network

networks:
  cruncho-network: